// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teelab.Models;

#nullable disable

namespace TeeLab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330101018_ThemSoLuongKho")]
    partial class ThemSoLuongKho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeeLab.Models.Nguoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nguois");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Nguoi");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Teelab.Models.ChiTietThanhToan", b =>
                {
                    b.Property<string>("MaTT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaTT", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("ChiTietThanhToans");
                });

            modelBuilder.Entity("Teelab.Models.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSP");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            MaSP = "AT001",
                            SoLuong = 50,
                            SoTien = 250000m,
                            TenSP = "Áo thun Teelab Basic",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AT002",
                            SoLuong = 10,
                            SoTien = 450000m,
                            TenSP = "Áo Hoodie Teelab",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "Hoc",
                            SoLuong = 0,
                            SoTien = 36000m,
                            TenSP = "Học",
                            TinhTrang = "Hết hàng"
                        });
                });

            modelBuilder.Entity("Teelab.Models.ThanhToan", b =>
                {
                    b.Property<string>("MaTT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaTT");

                    b.HasIndex("Id");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("TeeLab.Models.KhachHang", b =>
                {
                    b.HasBaseType("TeeLab.Models.Nguoi");

                    b.HasDiscriminator().HasValue("KhachHang");
                });

            modelBuilder.Entity("TeeLab.Models.NhanVien", b =>
                {
                    b.HasBaseType("TeeLab.Models.Nguoi");

                    b.HasDiscriminator().HasValue("NhanVien");
                });

            modelBuilder.Entity("TeeLab.Models.QuanLy", b =>
                {
                    b.HasBaseType("TeeLab.Models.Nguoi");

                    b.HasDiscriminator().HasValue("QuanLy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hoten = "Admin",
                            MatKhau = "123456",
                            Sdt = "0123456789",
                            TenDangNhap = "admin"
                        });
                });

            modelBuilder.Entity("Teelab.Models.ChiTietThanhToan", b =>
                {
                    b.HasOne("Teelab.Models.SanPham", "SanPham")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teelab.Models.ThanhToan", "ThanhToan")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("MaTT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("Teelab.Models.ThanhToan", b =>
                {
                    b.HasOne("TeeLab.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Teelab.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });

            modelBuilder.Entity("Teelab.Models.ThanhToan", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });
#pragma warning restore 612, 618
        }
    }
}
