// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teelab.Models;

#nullable disable

namespace TeeLab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405034830_InitialCreate_Final")]
    partial class InitialCreate_Final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeeLab.Models.Nguoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nguois");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Nguoi");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Teelab.Models.ChiTietThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("KichThuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MauSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaSP");

                    b.HasIndex("MaTT");

                    b.ToTable("ChiTietThanhToans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gia = 0.0,
                            KichThuoc = "M",
                            MaSP = "AT001",
                            MaTT = "HD_SAMPLE_01",
                            MauSac = "Đen",
                            SoLuong = 2
                        },
                        new
                        {
                            Id = 2,
                            Gia = 0.0,
                            KichThuoc = "XL",
                            MaSP = "HD001",
                            MaTT = "HD_SAMPLE_02",
                            MauSac = "Xám",
                            SoLuong = 1
                        });
                });

            modelBuilder.Entity("Teelab.Models.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KichThuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSP");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            MaSP = "AT001",
                            HinhAnh = "at001.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen, Trắng",
                            SoLuong = 50,
                            SoTien = 250000m,
                            TenSP = "Áo thun Teelab Basic",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AT002",
                            HinhAnh = "at002.jpg",
                            KichThuoc = "M, L",
                            MauSac = "Trắng",
                            SoLuong = 3,
                            SoTien = 290000m,
                            TenSP = "Áo thun Rabbit Edition",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "HD001",
                            HinhAnh = "hd001.jpg",
                            KichThuoc = "L, XL",
                            MauSac = "Xám",
                            SoLuong = 20,
                            SoTien = 450000m,
                            TenSP = "Hoodie Teelab Signature",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "PK001",
                            HinhAnh = "pk001.jpg",
                            KichThuoc = "Free size",
                            MauSac = "Đen",
                            SoLuong = 100,
                            SoTien = 150000m,
                            TenSP = "Mũ Cap Teelab",
                            TinhTrang = "Còn hàng"
                        });
                });

            modelBuilder.Entity("Teelab.Models.ThanhToan", b =>
                {
                    b.Property<string>("MaTT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTT");

                    b.HasIndex("Id");

                    b.ToTable("ThanhToans");

                    b.HasData(
                        new
                        {
                            MaTT = "HD_SAMPLE_01",
                            Id = 3,
                            NgayTao = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 500000m,
                            TrangThai = "Giao hàng thành công"
                        },
                        new
                        {
                            MaTT = "HD_SAMPLE_02",
                            Id = 3,
                            NgayTao = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 450000m,
                            TrangThai = "Chờ xác nhận"
                        });
                });

            modelBuilder.Entity("TeeLab.Models.KhachHang", b =>
                {
                    b.HasBaseType("TeeLab.Models.Nguoi");

                    b.Property<string>("HangThanhVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("KhachHang");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Avatar = "default-avatar.png",
                            Diachi = "Hải Phòng",
                            Email = "hoang@gmail.com",
                            Hoten = "Lê Minh Hoàng",
                            MatKhau = "123",
                            Sdt = "0977777777",
                            TenDangNhap = "hoang",
                            IsLocked = false
                        });
                });

            modelBuilder.Entity("TeeLab.Models.NhanVien", b =>
                {
                    b.HasBaseType("TeeLab.Models.Nguoi");

                    b.HasDiscriminator().HasValue("NhanVien");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Avatar = "default-avatar.png",
                            Diachi = "Hà Nội",
                            Email = "nhanvien@teelab.vn",
                            Hoten = "Nguyễn Nhân Viên",
                            MatKhau = "123",
                            Sdt = "0988888888",
                            TenDangNhap = "nhanvien"
                        });
                });

            modelBuilder.Entity("TeeLab.Models.QuanLy", b =>
                {
                    b.HasBaseType("TeeLab.Models.Nguoi");

                    b.HasDiscriminator().HasValue("QuanLy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "default-avatar.png",
                            Diachi = "Thái Nguyên",
                            Email = "admin@teelab.vn",
                            Hoten = "Dương Đình Hoàng",
                            MatKhau = "123",
                            Sdt = "0123456789",
                            TenDangNhap = "admin"
                        });
                });

            modelBuilder.Entity("Teelab.Models.ChiTietThanhToan", b =>
                {
                    b.HasOne("Teelab.Models.SanPham", "SanPham")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teelab.Models.ThanhToan", "ThanhToan")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("MaTT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("Teelab.Models.ThanhToan", b =>
                {
                    b.HasOne("TeeLab.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Teelab.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });

            modelBuilder.Entity("Teelab.Models.ThanhToan", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });
#pragma warning restore 612, 618
        }
    }
}
