// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teelab.Models;

#nullable disable

namespace TeeLab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeeLab.Models.ChatHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BotResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatHistory");
                });

            modelBuilder.Entity("TeeLab.Models.Nguoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nguois");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Nguoi");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Teelab.Models.ChiTietThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("KichThuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MauSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaSP");

                    b.HasIndex("MaTT");

                    b.ToTable("ChiTietThanhToans");
                });

            modelBuilder.Entity("Teelab.Models.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KichThuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSP");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            MaSP = "AT382",
                            HinhAnh = "aotrang.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen, Trắng, Xám tiêu",
                            MoTa = "Áo thun form oversize basic với chất liệu cotton 250GSM dày dặn, mềm mại và thoáng khí. Thiết kế trơn tối giản, dễ phối đồ, phù hợp mặc hằng ngày hoặc đi chơi.",
                            SoLuong = 50,
                            SoTien = 250000m,
                            TenSP = "Áo Thun Teelab Alter Oversize Cotton 250GSM Trơn Unisex TS382",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AT376",
                            HinhAnh = "aoxam.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Trắng, Xám",
                            MoTa = "Áo thun oversize với họa tiết World Tour TOKYO phong cách watercolor độc đáo. Chất cotton cao cấp mang lại cảm giác thoải mái, phù hợp cho phong cách streetwear năng động.",
                            SoLuong = 3,
                            SoTien = 280000m,
                            TenSP = "Áo Thun Teelab Alter Oversize Cotton In World Tour TOKYO Water Color Unisex TS376",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AT377",
                            HinhAnh = "aoxoc.jpg",
                            KichThuoc = "S, M ,L, XL",
                            MauSac = "Kẻ sọc nâu, Kẻ sọc xanh",
                            MoTa = "Áo thun sọc form rộng với điểm nhấn thêu Pop Star tinh tế. Chất liệu cotton mềm mại, thoáng mát, mang lại phong cách trẻ trung và cá tính.",
                            SoLuong = 20,
                            SoTien = 280000m,
                            TenSP = "Áo Thun Sọc Teelab Alter Oversize Cotton Thêu Pop Star Unisex TS377",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "Q003",
                            HinhAnh = "quandui.jpg",
                            KichThuoc = "S, M ,L ,XL",
                            MauSac = "Đen, Trắng",
                            MoTa = "Quần short nỉ form rộng với chất vải mềm mại, co giãn tốt. Thiết kế in World Tour nổi bật, phù hợp mặc đi chơi, thể thao hoặc ở nhà.",
                            SoLuong = 100,
                            SoTien = 220000m,
                            TenSP = "Quần Short Teelab Alter Oversize Nỉ Chân Cua In Wourld Tour Unisex SH003",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AT188",
                            HinhAnh = "soc.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen",
                            MoTa = "Áo thun oversize với họa tiết Wave Line hiện đại. Chất cotton cao cấp giúp thoáng mát, dễ chịu khi mặc. Thiết kế đơn giản nhưng vẫn tạo điểm nhấn.",
                            SoLuong = 0,
                            SoTien = 250000m,
                            TenSP = "Áo Thun Teelab Alter Oversize Cotton In Wave Line Unisex TS188",
                            TinhTrang = "Hết hàng"
                        },
                        new
                        {
                            MaSP = "Q131",
                            HinhAnh = "quanni.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen, Xanh Navy, Xám trắng",
                            MoTa = "Quần nỉ ống suông form rộng, mang lại sự thoải mái khi vận động. Họa tiết in World Tour tạo phong cách streetwear năng động.",
                            SoLuong = 50,
                            SoTien = 250000m,
                            TenSP = "Quần Nỉ Ống Suông Teelab Alter Oversize Nỉ In World Tour PS131",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "Q116",
                            HinhAnh = "quanbo.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen Wash, Trắng Wash, Xanh Wash, Xám đen Wash",
                            MoTa = "Quần jeans ống rộng phong cách local brand, dễ phối đồ. Chất denim bền bỉ, form rộng thoải mái phù hợp nhiều phong cách khác nhau.",
                            SoLuong = 20,
                            SoTien = 250000m,
                            TenSP = "Quần Dài Local Brand Unisex Teelab Jeans Ống Rộng PS116",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AH121",
                            HinhAnh = "hutdi.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen, Trắng, Xám, Nâu",
                            MoTa = "Hoodie zip form rộng với họa tiết Stars nổi bật. Chất nỉ dày dặn, giữ ấm tốt, phù hợp mặc trong thời tiết se lạnh.",
                            SoLuong = 6,
                            SoTien = 399000m,
                            TenSP = "Áo Teelab Local Brand Unisex Hoodie zip Stars HD121",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "PK085",
                            HinhAnh = "balo.jpg",
                            MoTa = "Balo da thiết kế tối giản, sang trọng. Chất liệu da bền đẹp, nhiều ngăn tiện dụng, phù hợp đi học, đi làm hoặc du lịch.",
                            SoLuong = 3,
                            SoTien = 340000m,
                            TenSP = "Balo Da Teelab Local Brand Essentials Leather Backpack AC085",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "PK057",
                            HinhAnh = "tat.jpg",
                            MauSac = "Đen, Trắng, Kem, Vàng, Xanh lá",
                            MoTa = "Tất cổ cao với thiết kế logo Teelab nổi bật. Chất liệu cotton co giãn tốt, thoáng khí, mang lại cảm giác dễ chịu khi sử dụng.",
                            SoLuong = 25,
                            SoTien = 25000m,
                            TenSP = "Tất Teelab Iconic Logo Socks AC057",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "PK112",
                            HinhAnh = "nonda.jpg",
                            MauSac = "Tweed Caro, Sọc, Đen, Da beo",
                            MoTa = "Nón pillbox phong cách vintage, tạo điểm nhấn cho outfit. Thiết kế độc đáo, dễ phối với nhiều phong cách thời trang.",
                            SoLuong = 26,
                            SoTien = 85000m,
                            TenSP = "Nón Pillbox Local Brand Unisex Teelab Alter AC112",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AT052",
                            HinhAnh = "SS052.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Hồng, Xanh, Xám",
                            MoTa = "Áo sơ mi ngắn tay chất Oxford cao cấp, form rộng thoải mái. Thiết kế đơn giản, phù hợp mặc đi học, đi làm hoặc đi chơi.",
                            SoLuong = 6,
                            SoTien = 250000m,
                            TenSP = "Áo Sơ Mi Ngắn Tay Teelab Local Brand Unisex Studio Oxford Shirt SS052",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AT066",
                            HinhAnh = "somidai.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen, Trắng, Xanh than, Xanh dương",
                            MoTa = "Áo sơ mi dài tay với chất liệu Oxford dày dặn, đứng form. Phù hợp phong cách lịch sự nhưng vẫn trẻ trung.",
                            SoLuong = 4,
                            SoTien = 280000m,
                            TenSP = "Áo Sơ Mi Dài Tay Teelab Local Brand Unisex Oxford shirts SS066",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AT068",
                            HinhAnh = "SS068.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen, Trắng, Xanh than, Xanh dương, Hồng",
                            MoTa = "Áo sơ mi cộc tay với thiết kế logo signature tinh tế. Chất liệu Oxford thân thiện, thoáng mát, phù hợp mặc hằng ngày.",
                            SoLuong = 12,
                            SoTien = 250000m,
                            TenSP = "Áo Sơ Mi Cộc Tay Teelab Local Brand Unisex Eco Oxford Logo Signature Shirt SS068",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AT074",
                            HinhAnh = "xamtieu.jpg",
                            KichThuoc = "M, L, XL",
                            MauSac = "Đen,Xanh Navy, Melane",
                            MoTa = "Áo polo dệt kim cao cấp với form vừa vặn. Thiết kế thanh lịch, phù hợp cho cả đi làm và đi chơi.",
                            SoLuong = 0,
                            SoTien = 320000m,
                            TenSP = "Áo Polo Local Brand Unisex Teelab KNIT POLO SHIRT AP074",
                            TinhTrang = "Hết hàng"
                        });
                });

            modelBuilder.Entity("Teelab.Models.ThanhToan", b =>
                {
                    b.Property<string>("MaTT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucTT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTT");

                    b.HasIndex("Id");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("TeeLab.Models.KhachHang", b =>
                {
                    b.HasBaseType("TeeLab.Models.Nguoi");

                    b.Property<string>("HangThanhVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("KhachHang");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Avatar = "default-avatar.png",
                            Diachi = "Hải Phòng",
                            Email = "Customer@gmail.com",
                            Hoten = "Customer",
                            MatKhau = "$2a$12$g9A8wOWOaOukKb52yMPeru.OAgvWjVQF6N7AkowgHFgSoeKjGAWtm",
                            Sdt = "0977777777",
                            TenDangNhap = "Customer",
                            IsLocked = false
                        });
                });

            modelBuilder.Entity("TeeLab.Models.NhanVien", b =>
                {
                    b.HasBaseType("TeeLab.Models.Nguoi");

                    b.HasDiscriminator().HasValue("NhanVien");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Avatar = "default-avatar.png",
                            Diachi = "Hà Nội",
                            Email = "Staff@teelab.vn",
                            Hoten = "Staff",
                            MatKhau = "$2a$12$g9A8wOWOaOukKb52yMPeru.OAgvWjVQF6N7AkowgHFgSoeKjGAWtm",
                            Sdt = "0988888888",
                            TenDangNhap = "Staff"
                        });
                });

            modelBuilder.Entity("TeeLab.Models.QuanLy", b =>
                {
                    b.HasBaseType("TeeLab.Models.Nguoi");

                    b.HasDiscriminator().HasValue("QuanLy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "default-avatar.png",
                            Diachi = "Thái Nguyên",
                            Email = "admin@teelab.vn",
                            Hoten = "ADMIN",
                            MatKhau = "$2a$12$g9A8wOWOaOukKb52yMPeru.OAgvWjVQF6N7AkowgHFgSoeKjGAWtm",
                            Sdt = "0123456789",
                            TenDangNhap = "admin"
                        });
                });

            modelBuilder.Entity("Teelab.Models.ChiTietThanhToan", b =>
                {
                    b.HasOne("Teelab.Models.SanPham", "SanPham")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("MaSP");

                    b.HasOne("Teelab.Models.ThanhToan", "ThanhToan")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("MaTT");

                    b.Navigation("SanPham");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("Teelab.Models.ThanhToan", b =>
                {
                    b.HasOne("TeeLab.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Teelab.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });

            modelBuilder.Entity("Teelab.Models.ThanhToan", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });
#pragma warning restore 612, 618
        }
    }
}
