// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teelab.Models;

#nullable disable

namespace TeeLab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeeLab.Models.Nguoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nguois");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Nguoi");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Teelab.Models.ChiTietThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("KichThuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MauSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaSP");

                    b.HasIndex("MaTT");

                    b.ToTable("ChiTietThanhToans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gia = 250000.0,
                            KichThuoc = "M",
                            MaSP = "TS382",
                            MaTT = "HD_SAMPLE_01",
                            MauSac = "Đen",
                            SoLuong = 2
                        },
                        new
                        {
                            Id = 2,
                            Gia = 399000.0,
                            KichThuoc = "XL",
                            MaSP = "HD121",
                            MaTT = "HD_SAMPLE_02",
                            MauSac = "Xám",
                            SoLuong = 1
                        });
                });

            modelBuilder.Entity("Teelab.Models.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KichThuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSP");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            MaSP = "TS382",
                            HinhAnh = "aotrang.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen, Trắng, Xám tiêu",
                            SoLuong = 50,
                            SoTien = 250000m,
                            TenSP = "Áo Thun Teelab Alter Oversize Cotton 250GSM Trơn Unisex TS382",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "TS376",
                            HinhAnh = "aoxam.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Trắng, Xám",
                            SoLuong = 3,
                            SoTien = 280000m,
                            TenSP = "Áo Thun Teelab Alter Oversize Cotton In World Tour TOKYO Water Color Unisex TS376",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "TS377",
                            HinhAnh = "aoxoc.jpg",
                            KichThuoc = "S, M ,L, XL",
                            MauSac = "Kẻ sọc nâu, Kẻ sọc xanh",
                            SoLuong = 20,
                            SoTien = 280000m,
                            TenSP = "Áo Thun Sọc Teelab Alter Oversize Cotton Thêu Pop Star Unisex TS377",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "TS379",
                            HinhAnh = "dodo.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen, Trắng, Xanh Navy, Đỏ đô, Xám tiêu",
                            SoLuong = 100,
                            SoTien = 250000m,
                            TenSP = "Áo Thun Teelab Alter Oversize Cotton In Essentials Unisex TS379",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "SH003",
                            HinhAnh = "quandui.jpg",
                            KichThuoc = "S, M ,L ,XL",
                            MauSac = "Đen, Trắng",
                            SoLuong = 100,
                            SoTien = 220000m,
                            TenSP = "Quần Short Teelab Alter Oversize Nỉ Chân Cua In Wourld Tour Unisex SH003",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "TS188",
                            HinhAnh = "soc.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen",
                            SoLuong = 0,
                            SoTien = 250000m,
                            TenSP = "Áo Thun Teelab Alter Oversize Cotton In Wave Line Unisex TS188",
                            TinhTrang = "Hết hàng"
                        },
                        new
                        {
                            MaSP = "PS131",
                            HinhAnh = "quanni.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen, Xanh Navy, Xám trắng",
                            SoLuong = 50,
                            SoTien = 250000m,
                            TenSP = "Quần Nỉ Ống Suông Teelab Alter Oversize Nỉ In World Tour PS131",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "PS116",
                            HinhAnh = "quanbo.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen Wash, Trắng Wash, Xanh Wash, Xám đen Wash",
                            SoLuong = 20,
                            SoTien = 250000m,
                            TenSP = "Quần Dài Local Brand Unisex Teelab Jeans Ống Rộng PS116",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "HD121",
                            HinhAnh = "hutdi.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen, Trắng, Xám, Nâu",
                            SoLuong = 6,
                            SoTien = 399000m,
                            TenSP = "Áo Teelab Local Brand Unisex Hoodie zip Stars HD121",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AC085",
                            HinhAnh = "balo.jpg",
                            SoLuong = 3,
                            SoTien = 340000m,
                            TenSP = "Balo Da Teelab Local Brand Essentials Leather Backpack AC085",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AC057",
                            HinhAnh = "tat.jpg",
                            MauSac = "Đen, Trắng, Kem, Vàng, Xanh lá",
                            SoLuong = 25,
                            SoTien = 25000m,
                            TenSP = "Tất Teelab Iconic Logo Socks AC057",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AC112",
                            HinhAnh = "nonda.jpg",
                            MauSac = "Tweed Caro, Sọc, Đen, Da beo",
                            SoLuong = 26,
                            SoTien = 85000m,
                            TenSP = "Nón Pillbox Local Brand Unisex Teelab Alter AC112",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AT001",
                            HinhAnh = "SS052.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Hồng, Xanh, Xám",
                            SoLuong = 6,
                            SoTien = 250000m,
                            TenSP = "Áo Sơ Mi Ngắn Tay Teelab Local Brand Unisex Studio Oxford Shirt SS052",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "HD001",
                            HinhAnh = "somidai.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen, Trắng, Xanh than, Xanh dương",
                            SoLuong = 4,
                            SoTien = 280000m,
                            TenSP = "Áo Sơ Mi Dài Tay Teelab Local Brand Unisex Oxford shirts SS066",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "SS068",
                            HinhAnh = "SS068.jpg",
                            KichThuoc = "S, M, L, XL",
                            MauSac = "Đen, Trắng, Xanh than, Xanh dương, Hồng",
                            SoLuong = 12,
                            SoTien = 250000m,
                            TenSP = "Áo Sơ Mi Cộc Tay Teelab Local Brand Unisex Eco Oxford Logo Signature Shirt SS068",
                            TinhTrang = "Còn hàng"
                        },
                        new
                        {
                            MaSP = "AP074",
                            HinhAnh = "xamtieu.jpg",
                            KichThuoc = "M, L, XL",
                            MauSac = "Đen,Xanh Navy, Melane",
                            SoLuong = 0,
                            SoTien = 320000m,
                            TenSP = "Áo Polo Local Brand Unisex Teelab KNIT POLO SHIRT AP074",
                            TinhTrang = "Hết hàng"
                        });
                });

            modelBuilder.Entity("Teelab.Models.ThanhToan", b =>
                {
                    b.Property<string>("MaTT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTT");

                    b.HasIndex("Id");

                    b.ToTable("ThanhToans");

                    b.HasData(
                        new
                        {
                            MaTT = "HD_SAMPLE_01",
                            Id = 3,
                            NgayTao = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 500000m,
                            TrangThai = "Giao hàng thành công"
                        },
                        new
                        {
                            MaTT = "HD_SAMPLE_02",
                            Id = 3,
                            NgayTao = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 450000m,
                            TrangThai = "Chờ xác nhận"
                        });
                });

            modelBuilder.Entity("TeeLab.Models.KhachHang", b =>
                {
                    b.HasBaseType("TeeLab.Models.Nguoi");

                    b.Property<string>("HangThanhVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("KhachHang");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Avatar = "default-avatar.png",
                            Diachi = "Hải Phòng",
                            Email = "hoang@gmail.com",
                            Hoten = "Lê Minh Hoàng",
                            MatKhau = "123",
                            Sdt = "0977777777",
                            TenDangNhap = "hoang",
                            IsLocked = false
                        });
                });

            modelBuilder.Entity("TeeLab.Models.NhanVien", b =>
                {
                    b.HasBaseType("TeeLab.Models.Nguoi");

                    b.HasDiscriminator().HasValue("NhanVien");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Avatar = "default-avatar.png",
                            Diachi = "Hà Nội",
                            Email = "nhanvien@teelab.vn",
                            Hoten = "Nguyễn Nhân Viên",
                            MatKhau = "123",
                            Sdt = "0988888888",
                            TenDangNhap = "nhanvien"
                        });
                });

            modelBuilder.Entity("TeeLab.Models.QuanLy", b =>
                {
                    b.HasBaseType("TeeLab.Models.Nguoi");

                    b.HasDiscriminator().HasValue("QuanLy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "default-avatar.png",
                            Diachi = "Thái Nguyên",
                            Email = "admin@teelab.vn",
                            Hoten = "Dương Đình Hoàng",
                            MatKhau = "123",
                            Sdt = "0123456789",
                            TenDangNhap = "admin"
                        });
                });

            modelBuilder.Entity("Teelab.Models.ChiTietThanhToan", b =>
                {
                    b.HasOne("Teelab.Models.SanPham", "SanPham")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teelab.Models.ThanhToan", "ThanhToan")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("MaTT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("Teelab.Models.ThanhToan", b =>
                {
                    b.HasOne("TeeLab.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Teelab.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });

            modelBuilder.Entity("Teelab.Models.ThanhToan", b =>
                {
                    b.Navigation("ChiTietThanhToans");
                });
#pragma warning restore 612, 618
        }
    }
}
